services:
  - type: web
    name: tic-tac-toe
    runtime: docker
    region: oregon
    plan: free
    branch: main
    rootDir: .
    dockerCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    autoDeploy: true
